### ISSUE TITLE
Cannot assign to read only property 'src' of layout:default.hbs

### ISSUE THREAD

**Issue by johjacb** [assemble/assemble#669]
I am using gulp assemble and started an issue there, but was sent here as it may be an assemble issue.

I've got this setup:
```
assemble.layouts(['./src/templates/layouts/*.hbs']);
assemble.partials(['./src/templates/partials/*.hbs']);
assemble.pages('./src/templates/pages/*.hbs');

gulp.task('assemble', function(){
	gulp.src('./src/templates/pages/*.hbs')
		.pipe(gulpAssemble(assemble))
		.pipe(gulp.dest(outputDir + ''))
		.pipe(reload({stream:true}));
})
```

I am seeing this error:
```
Error running middleware for default
TypeError: Cannot assign to read only property 'src' of layout:default.hbs
```

Am I missing something?

Thanks!

**Comment by jonschlinkert** [comment]
This is the second issue today related to layouts, I think a dependency got messed up or something. we're looking into it, thanks for letting us know

**Comment by jonschlinkert** [comment]
also try removing `assemble.pages('./src/templates/pages/*.hbs');` in the meantime, since technically you're double reading those files. once with `src` and once with `pages`

**Comment by doowb** [comment]
I pushed up a change, but I'm not sure that it's for this issue. Do you have a repo we can look at to reproduce the issue? Do you have any front matter in your pages or layouts?

**Comment by johjacb** [comment]
Unfortunately, I'm still seeing the error. I do have front matter:
```
---
title: LAYOUT
layout: default.hbs
---
```

I also removed the double pages call.

```
assemble.layouts(['./src/templates/layouts/*.hbs']);
assemble.partials(['./src/templates/partials/*.hbs']);

gulp.task('assemble', ['clean'], function(){
	gulp.src('./src/templates/pages/*.hbs')
		.pipe(gulpAssemble(assemble))
		.pipe(gulp.dest(outputDir + ''))
		.pipe(reload({stream:true}));
})
```

**Comment by jonschlinkert** [comment]
Did you clear your npm cache, node_modules, and reinstall everything from scratch? Also, where did you install assemble from?

**Comment by jonschlinkert** [comment]
wait, nvm this is the wrong repo. Please recreate the issue on gulp-assemble

**Comment by johjacb** [comment]
I'm happy to, although I was sent here from gulp-assemble :)

**Comment by jonschlinkert** [comment]
sorry about that, it looks like @doowb did indeed point you here, although I have no idea why. You're using gulp-assemble so even if there is a problem in assemble core the issue belongs on gulp-assemble.  we can create an issue here an link to that one if necessary. I'll just re-open the one you created there

**Comment by johjacb** [comment]
awesome - thanks for you help with this.
